about:
  home: https://trinotate.github.io/
  license: 'BSD'
  summary: 'Trinotate is a comprehensive annotation suite designed for automatic
    functional annotation of transcriptomes, particularly de novo assembled
    transcriptomes, from model or non-model organisms'

build:
  number: 0

package:
  name: trinotate
  version: '3.1.1'

requirements:
  build:
      - perl 
      - perl-app-cpanminus
      - perl-module-build
      - perl-dbi
      - perl-dbd-sqlite
      - perl-file-find-rule
  run:
      - perl 
      - sqlite
      - perl-app-cpanminus
      - perl-module-build
      - perl-dbi
      - perl-dbd-sqlite
      - blast
      - hmmer
      - perl-file-find-rule

source:
  fn: trinotate-trinotat-3.1.1.tar.gz
  url: https://github.com/Trinotate/Trinotate/archive/v3.1.1.tar.gz
  patches:
      - runMe.sh.patch
      - trinotate.patch
  md5: c36a7a26d6d7bfba8b6c8f7937055dc9

test:
    commands:
        - Trinotate --help 2>&1 | grep "Trinotate <sqlite.db> <command>"
